/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 12.0 		*/
/*  Created On : 04-dets-2018 08:53:37 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Create Tables */

CREATE TABLE Treeningu_kategooria_tuup(
	treeningu_kategooria_tuup_kood smallint NOT NULL,
	nimetus d_nimetus,
	CONSTRAINT PK_Treeningu_kategooria_tuup PRIMARY KEY (treeningu_kategooria_tuup_kood),
	CONSTRAINT AK_Treeningu_kategooria_tuup_nimetus UNIQUE (nimetus)
);

CREATE TABLE Treeningu_kategooria(
	treeningu_kategooria_kood smallint NOT NULL,
	nimetus d_nimetus,
	treeningu_kategooria_tuup_kood smallint NOT NULL,
	CONSTRAINT PK_Treeningu_kategooria PRIMARY KEY (treeningu_kategooria_kood),
	CONSTRAINT AK_Treeningu_kategooria_nimetus_Treeningu_kategooria_tuup_kood UNIQUE (treeningu_kategooria_tuup_kood,nimetus),
	CONSTRAINT FK_Treeningu_kategooria_Treeningu_kategooria_tuup FOREIGN KEY (treeningu_kategooria_tuup_kood) REFERENCES Treeningu_kategooria_tuup (treeningu_kategooria_tuup_kood) ON DELETE No Action ON UPDATE Cascade
);

CREATE TABLE Treeningu_seisundi_liik(
	treeningu_seisundi_liik_kood smallint NOT NULL,
	nimetus d_nimetus,
	CONSTRAINT PK_Treeningu_seisundi_liik PRIMARY KEY (treeningu_seisundi_liik_kood),
	CONSTRAINT AK_Treeningu_seisundi_liik_nimetus UNIQUE (nimetus)
);

CREATE TABLE Tootaja_seisundi_liik(
	tootaja_seisundi_liik_kood smallint NOT NULL,
	nimetus d_nimetus,
	CONSTRAINT PK_Tootaja_seisundi_liik PRIMARY KEY (tootaja_seisundi_liik_kood),
	CONSTRAINT AK_Tootaja_seisundi_liik UNIQUE (nimetus)
);

CREATE TABLE Kliendi_seisundi_liik(
	kliendi_seisundi_liik_kood smallint NOT NULL,
	nimetus d_nimetus,
	CONSTRAINT PK_Kliendi_seisundi_liik PRIMARY KEY (kliendi_seisundi_liik_kood),
	CONSTRAINT AK_Kliendi_seisundi_liik_nimetus UNIQUE (nimetus)
);

CREATE TABLE Isiku_seisundi_liik(
	isiku_seisundi_liik_kood smallint NOT NULL,
	nimetus d_nimetus,
	CONSTRAINT PK_Isiku_seisundi_liik PRIMARY KEY (isiku_seisundi_liik_kood),
	CONSTRAINT AK_Isiku_seisundi_liik_nimetus UNIQUE (nimetus)
);

CREATE TABLE Riik(
	riik_kood varchar(3)	NOT NULL,
	nimetus d_nimetus,
	CONSTRAINT PK_Riik PRIMARY KEY (riik_kood),
	CONSTRAINT AK_Riik_nimetus UNIQUE (nimetus),
	CONSTRAINT CHK_Riik_riik_kood_koosneb_kolmest_suurest_tahest CHECK ((riik_kood~'^[A-Z]{3}$'))
);

CREATE TABLE Amet(
	amet_kood smallint NOT NULL,
	nimetus d_nimetus,
	kirjeldus text,
	CONSTRAINT PK_Amet PRIMARY KEY (amet_kood),
	CONSTRAINT AK_Amet_nimetus UNIQUE (nimetus),
	CONSTRAINT CHK_Amet_kirjeldus_ei_koosne_tyhikutest_pole_tyhi CHECK (kirjeldus !~ '^[[:space:]]*$')
) WITH ( OIDS = FALSE, FILLFACTOR = 90) TABLESPACE pg_default;

CREATE TABLE Isik(
	isik_id serial NOT NULL,
	isikukood varchar(60)	 NOT NULL,
	riik_kood varchar(3)	 NOT NULL,
	meil varchar(254)	 NOT NULL,
	parool varchar(60)	 NOT NULL,
	isiku_seisundi_liik_kood smallint NOT NULL DEFAULT 1,
	sunni_kp date NOT NULL,
	reg_aeg d_reg_aeg,
	eesnimi varchar(1000)	 NULL,
	perenimi varchar(1000)	 NULL,
	elukoht varchar(1000)	 NULL,
	CONSTRAINT PK_Isik PRIMARY KEY (isik_id),
	CONSTRAINT AK_Isik_meil UNIQUE (meil),
	CONSTRAINT AK_Isik_isikukood_riik_kood UNIQUE (isikukood),
	CONSTRAINT CHK_Isik_eesnimi_perenimi_on_olemas CHECK ((eesnimi IS NOT NULL) OR (perenimi IS NOT NULL)),
	CONSTRAINT CHK_Isik_meil_oige_struktuur CHECK (meil::text ~ '^.*@.*$'::text AND meil::text !~ '^.*@.*@.*$'::text),
	CONSTRAINT CHK_Isik_sunni_kp_vahemik CHECK (sunni_kp >='1900-01-01' AND sunni_kp <= '2100-12-31'),
	CONSTRAINT CHK_Isik_sunni_kp_vahem_kui_praegu CHECK (sunni_kp <= reg_aeg),
	CONSTRAINT CHK_Isik_isikukood_ei_koosne_tyhikutest_pole_tyhi CHECK (isikukood!~'^[[:space:]]*$'),
	CONSTRAINT CHK_Isik_isikukood_lubatud_symbolid CHECK (isikukood::text ~* '^[a-z0-9 /-]+$'::text),
	CONSTRAINT CHK_Isik_eesnimi_ei_koosne_tyhikutest_pole_tyhi CHECK (eesnimi !~ '^[[:space:]]+$'),
	CONSTRAINT CHK_Isik_perenimi_ei_koosne_tyhikutest_pole_tyhi CHECK ((perenimi !~ '^[[:space:]]+$')),
	CONSTRAINT CHK_Isik_elukoht_ei_koosne_tyhikutest_pole_tyhi CHECK ((elukoht !~ '^[[:space:]]+$')),
	CONSTRAINT CHK_Isik_elukoht_ei_koosne_ainult_numritest CHECK (elukoht !~ '^[[:digit:]]+$'),
	CONSTRAINT CHK_Isik_parool_ei_koosne_tyhikutest_pole_tyhi CHECK (parool!~'^[[:space:]]*$'),
	CONSTRAINT FK_Isiku_seisundi_liik FOREIGN KEY (isiku_seisundi_liik_kood) REFERENCES Isiku_seisundi_liik (isiku_seisundi_liik_kood) ON DELETE No Action ON UPDATE Cascade,
	CONSTRAINT FK_Isik_Riik FOREIGN KEY (riik_kood) REFERENCES Riik (riik_kood) ON DELETE No Action ON UPDATE Cascade
) WITH ( OIDS = FALSE, FILLFACTOR = 90) TABLESPACE pg_default;

CREATE TABLE Klient(
	klient_id integer NOT NULL,
	kliendi_seisundi_liik_kood smallint NOT NULL DEFAULT 1,
	on_nous_tylitamisega boolean NOT NULL DEFAULT False,
	CONSTRAINT PK_Klient PRIMARY KEY (klient_id),
	CONSTRAINT FK_Klient_Isik FOREIGN KEY (klient_id) REFERENCES Isik (isik_id) ON DELETE Cascade ON UPDATE No Action,
	CONSTRAINT FK_Klient_Kliendi_seisundi_liik FOREIGN KEY (kliendi_seisundi_liik_kood) REFERENCES Kliendi_seisundi_liik (kliendi_seisundi_liik_kood) ON DELETE No Action ON UPDATE Cascade
) WITH ( OIDS = FALSE, FILLFACTOR = 90) TABLESPACE pg_default;

CREATE TABLE Tootaja(
	isik_id integer NOT NULL,
	amet_kood smallint NOT NULL,
	tootaja_seisundi_liik_kood smallint NOT NULL DEFAULT 1,
	mentor integer,
	CONSTRAINT PK_Tootaja PRIMARY KEY (isik_id),
	CONSTRAINT CHK_Tootaja_mentor CHECK (isik_id <> mentor),
	CONSTRAINT FK_Tootaja_Amet FOREIGN KEY (amet_kood) REFERENCES Amet (amet_kood) ON DELETE No Action ON UPDATE Cascade,
	CONSTRAINT FK_Tootaja_Isik FOREIGN KEY (isik_id) REFERENCES Isik (isik_id) ON DELETE Cascade ON UPDATE No Action,
	CONSTRAINT FK_Tootaja_Tootaja_seisundi_liik FOREIGN KEY (tootaja_seisundi_liik_kood) REFERENCES Tootaja_seisundi_liik (tootaja_seisundi_liik_kood) ON DELETE No Action ON UPDATE Cascade,
	CONSTRAINT FK_Tootaja FOREIGN KEY (mentor) REFERENCES Tootaja (isik_id) ON DELETE Set Null ON UPDATE No Action
) WITH ( OIDS = FALSE, FILLFACTOR = 90) TABLESPACE pg_default;

CREATE TABLE Treeningu_tuup(
	treeningu_tuup_kood smallint NOT NULL,
	nimetus d_nimetus,
	CONSTRAINT PK_Treeningu_tuup PRIMARY KEY (treeningu_tuup_kood),
	CONSTRAINT AK_Treeningu_tuup_nimetus UNIQUE (nimetus)
);

CREATE TABLE Treening(
	treeningu_kood smallint NOT NULL,
	nimetus d_nimetus,
	reg_id integer NOT NULL,
	treeningu_seisundi_liik_kood smallint NOT NULL DEFAULT 1,
	treeningu_tuup_kood smallint NOT NULL,
	reg_aeg d_reg_aeg,
	kestus smallint NOT NULL,
	CONSTRAINT PK_Treening PRIMARY KEY (treeningu_kood),
	CONSTRAINT AK_Treening_nimetus UNIQUE (nimetus),
	CONSTRAINT CHK_Treening_kestus_oige_vahemik CHECK (kestus >=30 AND kestus <=90),
	CONSTRAINT FK_Treening_Tootaja FOREIGN KEY (reg_id) REFERENCES Tootaja (isik_id) ON DELETE No Action ON UPDATE No Action,
	CONSTRAINT FK_Treening_Treeningu_seisundi_liik FOREIGN KEY (treeningu_seisundi_liik_kood) REFERENCES Treeningu_seisundi_liik (treeningu_seisundi_liik_kood) ON DELETE No Action ON UPDATE Cascade,
	CONSTRAINT FK_Treening_Treeningu_tuup FOREIGN KEY (treeningu_tuup_kood) REFERENCES Treeningu_tuup (treeningu_tuup_kood) ON DELETE No Action ON UPDATE Cascade
) WITH (OIDS = FALSE, FILLFACTOR = 90) TABLESPACE pg_default;


CREATE TABLE Treeningu_kategooria_omamine(
	treeningu_kategooria_omamine_id SERIAL,
	treeningu_kood smallint NOT NULL,
	treeningu_kategooria_kood smallint NOT NULL,
	CONSTRAINT PK_Treeningu_kategooria_omamine_Treeningu_kategooria_omamine_id PRIMARY KEY (treeningu_kategooria_omamine_id),
	CONSTRAINT AK_Treeningu_kategooria_omamine_Treeningu_katogooria_Treening UNIQUE (treeningu_kood, treeningu_kategooria_kood),
	CONSTRAINT FK_Treeningu_kategooria_omamine_Treening FOREIGN KEY (treeningu_kood) REFERENCES Treening (treeningu_kood) ON DELETE Cascade ON UPDATE Cascade,
	CONSTRAINT FK_Treeningu_kategooria_omamine_Treeningu_kategooria FOREIGN KEY (treeningu_kategooria_kood) REFERENCES Treeningu_kategooria (treeningu_kategooria_kood) ON DELETE No Action ON UPDATE Cascade
);


CREATE INDEX IXFK_Isik_Isiku_seisundi_liik ON Isik (isiku_seisundi_liik_kood ASC);
CREATE INDEX IXFK_Isik_Riik ON Isik (riik_kood ASC);
CREATE INDEX IXFK_Klient_kliendi_seisundi_liik ON Klient (kliendi_seisundi_liik_kood ASC);
CREATE INDEX IXFK_Tootaja_seisundi_liik ON Tootaja (tootaja_seisundi_liik_kood ASC);
CREATE INDEX IXFK_Tootaja_amet ON Tootaja (amet_kood ASC);
CREATE INDEX IXFK_Tootaja_mentor ON Tootaja (mentor ASC);
CREATE INDEX IXFK_Treening_Tootaja ON Treening (reg_id ASC);
CREATE INDEX IXFK_Treening_tuup ON Treening (treeningu_tuup_kood ASC);
CREATE INDEX IXFK_Treening_seisundi_liik ON Treening (treeningu_seisundi_liik_kood ASC);
CREATE INDEX IXFK_Treeningu_kategooria_omamine_Treeningu_kategooria_kood ON Treeningu_kategooria_omamine (treeningu_kategooria_kood ASC);

CREATE INDEX IXFK_Isik_perenimi ON Isik (perenimi);
CREATE INDEX IXFK_Isik_eesnimi ON Isik (eesnimi);


ALTER TABLE Isik DROP CONSTRAINT AK_Isik_meil;
CREATE UNIQUE INDEX AK_Isik_meil ON Isik (Upper(meil));


CREATE ROLE t164027_juhataja WITH LOGIN PASSWORD 'parool';

ALTER TABLE Isik ADD CONSTRAINT CHK_Isik_parool_ei_koosne_tyhikutest_pole_tyhi CHECK (parool!~'^[[:space:]]*$');